# 정렬
- 배열 값을 기준에 따라 순서대로 배치하는 작업임
- 오름차순/내림차순 정렬 가능함
- 원본 유지 여부 확인 필요함


In [1]:
import numpy as np
from selenium.webdriver.support.expected_conditions import none_of

In [2]:
# np.sort(ndarray)
# - 정렬된 새 배열을 반환
# - 원본 배열은 유지
# - 원본 데이터 유지 여부는 데이터 전처리에 있어서 중요한 부분
arr = np.random.randint(1, 11, 10)
print('arr :', arr)
print('np.sort :', np.sort(arr)) # 정렬 -> 오름차순
print('arr : ', arr) # 원본 유지 확인

arr : [9 5 1 4 7 9 2 9 3 2]
np.sort : [1 2 2 3 4 5 7 9 9 9]
arr :  [9 5 1 4 7 9 2 9 3 2]


In [3]:
# 내림차순(역순 정렬) -> 슬라이싱 방식 이용
# 출력값들 사이에 ,가 찍혀있으면 list 없다면 ndarray
np.sort(arr)[:: -1]

array([9, 9, 9, 7, 5, 4, 3, 2, 2, 1])

In [4]:
# 2차원 배열 형태의 데이터 정렬
# - axis에 따라 정렬 기준이 달라짐
# - axis = None - 전체(1차원으로 변경 후 전체 정렬)
# - axis = 0    - 각 행 안에서 열 방향으로 정렬
# - axis = 1    - 각 열 안에서 행 방향으로 정렬

np.random.seed(1)
arr = np.random.randint(1, 15, (3, 4))
print(arr)

print("np.sort(arr, axis=None)")
print(np.sort(arr, axis=None))

print("np.sort(arr, axis=0)")
print(np.sort(arr, axis=0))

print("np.sort(arr, axis=1)")
print(np.sort(arr, axis=1))

[[ 6 12 13  9]
 [10 12  6  1]
 [ 1  2 13  8]]
np.sort(arr, axis=None)
[ 1  1  2  6  6  8  9 10 12 12 13 13]
np.sort(arr, axis=0)
[[ 1  2  6  1]
 [ 6 12 13  8]
 [10 12 13  9]]
np.sort(arr, axis=1)
[[ 6  9 12 13]
 [ 1  6 10 12]
 [ 1  2  8 13]]


## np.argsort()
- 배열 요소를 정렬했을 때의 인덱스를 반환함
- 정렬된 값 자체가 아니라 정렬 순서임
- 실제 정렬값은 `arr[indices]`처럼 다시 인덱싱해야 함


In [5]:
# argsort()의 결과값은 정렬 순서를 만드는 인덱스

arr = np.array([40, 10, 20, 30])
indices = np.argsort(-arr) # == arr * -1
print(indices)
print(arr[indices])

[0 3 2 1]
[40 30 20 10]


In [6]:
# 2차원 argsort(axis = 0)
arr = np.array([[30, 20, 10],
                [60, 40, 50]])
indices = np.argsort(arr, axis=0)
print(indices)

[[0 0 0]
 [1 1 1]]


In [7]:
arr = np.array([[30, 20, 10],
                [60, 40, 50]])
indices = np.argsort(arr, axis=1)
print(indices)

[[2 1 0]
 [1 2 0]]


In [8]:
# 각 배열의 같은 인덱스 요소가 한 학생의 이름, 점수를 나타내고 있음
# 학생의 이름으로 점수 내림차순 정렬
names = np.array(['홍길동', '신사임당', '이순신', '유관순'])
scores = np.array([90, 30, 50, 70])

# ['홍길동' '유관순' '이순신' '신사임당']
indices = np.argsort(-scores)
print(names[indices])
print(scores[indices])

['홍길동' '유관순' '이순신' '신사임당']
[90 70 50 30]


In [9]:
# 우선순위에 따른 작업 정렬(작은 수 일수록 높은 우선 순위)
priorities = np.array([3, 1, 2, 5, 4])
tasks = np.array(["Task A", "Task B", "Task C", "Task D", "Task E"])


# 결과: ["Task B" "Task C" "Task A" "Task E" "Task D"]

# indices = np.argsort(priorities)
# sorted_tasks = tasks[indices]
#
# print(sorted_tasks)

print(tasks[np.argsort(priorities)])

['Task B' 'Task C' 'Task A' 'Task E' 'Task D']
