# [7] Numpy 종합 실습

다음은 5개 지점에서 판매된 과일에 대한 월별 판매량 데이터입니다. 이 데이터는 각 지점의 판매량을 월별로 나타내며, 각 지점에서 판매된 사과, 바나나, 오렌지의 판매량이 기록되어 있습니다. 이 데이터를 사용하여 여러 가지 통계적 분석과 배열 조작을 수행하세요.

1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.

- **데이터 (**각 지점의 월별 과일 판매량(단위: 개))

    ```python
    import numpy as np

    # 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
    # 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
    sales_data = np.array([
        # 지점 1
        [[120, 150, 200, 230, 180, 210],  # 사과 판매량
         [100, 140, 170, 190, 160, 180],  # 바나나 판매량
         [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

        # 지점 2
        [[80, 90, 110, 140, 130, 120],
         [60, 70, 90, 100, 110, 95],
         [50, 80, 100, 110, 90, 85]],

        # 지점 3
        [[130, 140, 160, 180, 170, 190],
         [110, 120, 130, 150, 140, 160],
         [100, 110, 120, 130, 120, 140]],

        # 지점 4
        [[100, 130, 150, 170, 160, 180],
         [90, 100, 110, 120, 130, 125],
         [80, 110, 140, 130, 120, 110]],

        # 지점 5
        [[90, 110, 130, 140, 120, 130],
         [70, 85, 100, 110, 105, 95],
         [60, 90, 110, 100, 90, 95]]
    ])
    ```

In [1]:
import numpy as np

# 데이터 구조: (지점, 과일, 월)
# 5개 지점 × 3개 과일 × 6개월
sales_data = np.array([
    # 지점 1
    [
        [120, 150, 200, 230, 180, 210],  # 사과
        [100, 140, 170, 190, 160, 180],  # 바나나
        [90, 120, 160, 140, 130, 150]    # 오렌지
    ],

    # 지점 2
    [
        [80, 90, 110, 140, 130, 120],
        [60, 70, 90, 100, 110, 95],
        [50, 80, 100, 110, 90, 85]
    ],

    # 지점 3
    [
        [130, 140, 160, 180, 170, 190],
        [110, 120, 130, 150, 140, 160],
        [100, 110, 120, 130, 120, 140]
    ],

    # 지점 4
    [
        [100, 130, 150, 170, 160, 180],
        [90, 100, 110, 120, 130, 125],
        [80, 110, 140, 130, 120, 110]
    ],

    # 지점 5
    [
        [90, 110, 130, 140, 120, 130],
        [70, 85, 100, 110, 105, 95],
        [60, 90, 110, 100, 90, 95]
    ]
])

# fruits = np.array(["사과", "바나나", "오렌지"])
#
# # ==================================================
# # 1. 각 지점에서 과일별 6개월 평균 판매량
# # ==================================================
#
# print("=" * 50)
# print("1. 지점별 과일 평균 판매량")
# print("=" * 50)
#
# # 월 축(axis=2)을 기준으로 평균 계산
# average_sales = sales_data.mean(axis=2)
#
# for branch_index, branch_average in enumerate(average_sales):
#     print(f"\n지점 {branch_index + 1}")
#
#     for fruit_index, average in enumerate(branch_average):
#         print(f"  {fruits[fruit_index]}: {average:.2f}개")
#
#
# # ==================================================
# # 2. 각 월마다 전체 지점에서 가장 많이 판매된 과일
# # ==================================================
#
# print("\n" + "=" * 50)
# print("2. 월별 최다 판매 과일")
# print("=" * 50)
#
# # 지점 축(axis=0)을 합산
# # 결과 배열 형태: (과일 3개, 월 6개)
# monthly_fruit_totals = sales_data.sum(axis=0)
#
# # 각 월에서 가장 판매량이 큰 과일의 인덱스
# monthly_max_indices = monthly_fruit_totals.argmax(axis=0)
#
# # 각 월의 최대 판매량
# monthly_max_sales = monthly_fruit_totals.max(axis=0)
#
# for month in range(sales_data.shape[2]):
#     fruit_index = monthly_max_indices[month]
#     amount = monthly_max_sales[month]
#
#     print(
#         f"{month + 1}월: "
#         f"{fruits[fruit_index]} - {amount}개"
#     )
#
#
# # ==================================================
# # 3. 과일별 6개월 전체 판매량 및 최다 판매 과일
# # ==================================================
#
# print("\n" + "=" * 50)
# print("3. 과일별 전체 판매량")
# print("=" * 50)
#
# # 지점 축(axis=0)과 월 축(axis=2)을 합산
# fruit_totals = sales_data.sum(axis=(0, 2))
#
# for fruit, total in zip(fruits, fruit_totals):
#     print(f"{fruit}: {total}개")
#
# # 전체 판매량이 가장 큰 과일
# best_fruit_index = fruit_totals.argmax()
#
# print(
#     f"\n가장 많이 판매된 과일은 "
#     f"{fruits[best_fruit_index]}이며, "
#     f"총판매량은 {fruit_totals[best_fruit_index]}개입니다."
# )
#
#
# # ==================================================
# # 4. 판매량이 150개 이상인 데이터 추출
# # ==================================================
#
# print("\n" + "=" * 50)
# print("4. 판매량이 150개 이상인 데이터")
# print("=" * 50)
#
# # 조건을 만족하는 위치 반환
# # 각 행: [지점 인덱스, 과일 인덱스, 월 인덱스]
# positions = np.argwhere(sales_data >= 150)
#
# for branch_index, fruit_index, month_index in positions:
#     amount = sales_data[
#         branch_index,
#         fruit_index,
#         month_index
#     ]
#
#     print(
#         f"지점 {branch_index + 1}, "
#         f"{fruits[fruit_index]}, "
#         f"{month_index + 1}월: "
#         f"{amount}개"
#     )
#
#


1. 지점별 과일 평균 판매량

지점 1
  사과: 181.67개
  바나나: 156.67개
  오렌지: 131.67개

지점 2
  사과: 111.67개
  바나나: 87.50개
  오렌지: 85.83개

지점 3
  사과: 161.67개
  바나나: 135.00개
  오렌지: 120.00개

지점 4
  사과: 148.33개
  바나나: 112.50개
  오렌지: 115.00개

지점 5
  사과: 120.00개
  바나나: 94.17개
  오렌지: 90.83개

2. 월별 최다 판매 과일
1월: 사과 - 520개
2월: 사과 - 620개
3월: 사과 - 750개
4월: 사과 - 860개
5월: 사과 - 760개
6월: 사과 - 830개

3. 과일별 전체 판매량
사과: 4340개
바나나: 3515개
오렌지: 3260개

가장 많이 판매된 과일은 사과이며, 총판매량은 4340개입니다.

4. 판매량이 150개 이상인 데이터
지점 1, 사과, 2월: 150개
지점 1, 사과, 3월: 200개
지점 1, 사과, 4월: 230개
지점 1, 사과, 5월: 180개
지점 1, 사과, 6월: 210개
지점 1, 바나나, 3월: 170개
지점 1, 바나나, 4월: 190개
지점 1, 바나나, 5월: 160개
지점 1, 바나나, 6월: 180개
지점 1, 오렌지, 3월: 160개
지점 1, 오렌지, 6월: 150개
지점 3, 사과, 3월: 160개
지점 3, 사과, 4월: 180개
지점 3, 사과, 5월: 170개
지점 3, 사과, 6월: 190개
지점 3, 바나나, 4월: 150개
지점 3, 바나나, 6월: 160개
지점 4, 사과, 3월: 150개
지점 4, 사과, 4월: 170개
지점 4, 사과, 5월: 160개
지점 4, 사과, 6월: 180개


In [2]:
#1번

fruits = np.array(["사과", "바나나", "오렌지"])
branches = np.array(["지점1", "지점2", "지점3", "지점4", "지점5"])
months = np.array(["1월", "2월", "3월", "4월", "5월", "6월"])

branch_avg = np.mean(sales_data, axis=2) # 각 지점 과일별 판매 평균
print(branch_avg)

print("각 지점 과일 6개월 판매 평균")
for b_index, b_name in enumerate(branches):
    print(b_name)
    for f_index, f_name in enumerate(fruits):
        print(f"{f_name} : {branch_avg[b_index][f_index]: .2f}")

[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]
각 지점 과일 6개월 판매 평균
지점1
사과 :  181.67
바나나 :  156.67
오렌지 :  131.67
지점2
사과 :  111.67
바나나 :  87.50
오렌지 :  85.83
지점3
사과 :  161.67
바나나 :  135.00
오렌지 :  120.00
지점4
사과 :  148.33
바나나 :  112.50
오렌지 :  115.00
지점5
사과 :  120.00
바나나 :  94.17
오렌지 :  90.83


In [3]:
#2번

bested_fruits = np.argmax(monthly_fruit_totals, axis=1)


print("각 월마다 전체 지점에서 가장 많이 판매된 과일명/판매량")
for m_index, m_name in enumerate(months):
    fruit_index = bested_fruits[m_index]
    fruit_name = fruits[fruit_index]
    sales_amount = monthly_fruit_totals[fruit_index, m_index]
    print(f"{m_name} : {fruit_name} / {sales_amount}")

각 월마다 전체 지점에서 가장 많이 판매된 과일명/판매량


IndexError: index 3 is out of bounds for axis 0 with size 3